kpsUowRmqTest.Web/Models/ErrorViewModel.cs
using System;

namespace kpsUowRmqTest.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

kpsUowRmqTest.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using kpsUowRmqTest.Web.Models;

namespace kpsUowRmqTest.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

kpsUowRmqTest.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using kpsUowRmqTest.Web.Models;
using kpsUowRmqTest.Data.Interfaces;

namespace kpsUowRmqTest.Web.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

kpsUowRmqTest.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using kpsUowRmqTest.Web.Models;
using kpsUowRmqTest.Data.Interfaces;

namespace kpsUowRmqTest.Web.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
               
        public IActionResult Details()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

kpsUowRmqTest.Web/ViewComponents/MenuViewComponent.cs
using kpsUowRmqTest.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kpsUowRmqTest.Web.ViewComponents
{
    public class MenuViewComponent:ViewComponent
    {
        //private readonly IUnitOfWork _unitOfWork;
        //public MenuViewComponent(IUnitOfWork unitOfWork)
        //{
        //    _unitOfWork = unitOfWork;
        //}
        public IViewComponentResult Invoke()
        {
            //var menu = _unitOfWork.LeftMenuRepository.Get();
            //return View(menu);
            return View();
        }
    }
}

kpsUowRmqTest.Web/Views/Home/Index.cshtml

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>


@*<input type="button" name="name" value="Token Al" onclick="getToken();" />
<br />
<input type="button" name="name" value="Token gönder, bir ürün al" onclick="getProduct();" />
<br />
<input type="button" name="name" value="Token gönder, tüm ürünleri getir" onclick="getValues();" />



<br />
<input type="text" name="name" value="" id="Token" />
<br />

<br />
<input type="text" name="name" value="" id="Name" placeholder="Ad"/>
<br />
<input type="text" name="surname" value="" id="Surname" placeholder="Soyad"/>
<br />
<input type="text" name="tckn" value="" id="TCKN" placeholder="TCKN"/>
<br />
<input type="text" name="year" value="" id="Year" placeholder="Yıl"/>
<br />
<input type="button" name="name" value="User gonder" onclick="postUser();" />*@


<script>
    window.Token = null;
    //  http://localhost:50619/api/Authentication/request  buradan token al
    //http://localhost:50619/api/values                  burada token ı kullan
    function getToken() {
        $.ajax({
            type: 'POST',
            url: 'http://localhost:50619/api/Authentication/request',
            data: '{username:"x", password:"y"}',
            contentType: 'application/json',
            success: function (resultData) {
                window.Token = resultData;
                $("#Token").val(resultData);
            },
            error: function (resultData) {
                console.log(resultData);
            }
        });
    }
    function getValues() {
        $.ajax({
            type: 'GET',
            //url: 'http://localhost:50619/api/values',
            url: 'http://localhost:50619/api/product',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            data: {},
            success: function (data) {
                //$.each(data, function (i) {
                //    console.log(data[i].name);
                //})
                alert("başarılı getvalues");
                for (var i = 0; i < data.length; i++) {
                    postValues(data[i]);
                }
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function getProduct() {
        $.ajax({
            type: 'GET',
            url: 'http://localhost:50619/api/product/3',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            data: {},
            success: function (data) {
                console.log(data);
                postValues(data);
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function postValues(data) {
        $.ajax({
            type: 'POST',
            //url: 'http://localhost:50619/api/values',
            //url: 'http://localhost:50619/api/product/1',
            //url: 'http://localhost:50619/api/product',
            url:'http://localhost:57374/api/products',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            contentType: 'application/json',
            dataType: 'json',
            //data: JSON.stringify({ Price: 67, Name: "aaaaaaa", Category: "ff" }),
            data: JSON.stringify(data),
            success: function (data) {
                console.log(data);
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function deleteProduct() {
        $.ajax({
            type: 'DELETE',
            //url: 'http://localhost:50619/api/values',
            //url: 'http://localhost:50619/api/product/1',
            url: 'http://localhost:50619/api/product/2',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            contentType: 'application/json',
            //data: JSON.stringify({ Price: 23, Name: "fdf", Category: "ff" }),
            data: {},
            success: function (data) {
                console.log(data);
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function putProduct() {
        $.ajax({
            type: 'PUT',
            url: 'http://localhost:50619/api/product/2',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            contentType: 'application/json',
            data: JSON.stringify({Id:2, Price: 11, Name: "g", Category: "r" }),
            success: function (data) {
                console.log(data);
            },
            error: function (data) {
                console.log(data);
            }
        });
    }

    function postUser() {

        var TCKN = $("#TCKN").val();
        var Surname = $("#Surname").val();
        var Name = $("#Name").val();
        var Year = $("#Year").val();

        var objMainModel = {};

        objMainModel.Year = Year;
        objMainModel.Surname = Surname;
        objMainModel.Name = Name;
        objMainModel.TCKN = TCKN;     
        
                $.ajax({
                    type: "POST",
                    url: 'http://localhost:57374/api/users',
                    data: JSON.stringify(objMainModel),
                    contentType: 'application/json',
                    success: function (response) {
                  
                    //    if (response.IsSuccess) {
                    //        $("#txt-Name").val(response.Name);
                    //        $("#txt-Surname").val(response.Surname);
                    //        hideLoader();
                    //}
                },
                failure: function (response) {
                    alert(response.responseText);
                }
            });
        
    }
</script>

kpsUowRmqTest.Web/Views/Product/Details.cshtml

@{
    ViewData["Title"] = "Details";
}

<h1>Product Details</h1>


<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>


<input type="button" name="name" value="Token Al" onclick="getToken();" />
<br />
<input type="button" name="name" value="Token gönder, bir ürün al" onclick="getProduct();" />
<br />
<input type="button" name="name" value="Token gönder, tüm ürünleri getir" onclick="getValues();" />
@*<br />
    <input type="button" name="name" value="add product" onclick="postValues();" />
    <br />
    <input type="button" name="name" value="update product" onclick="putProduct();" />
    <br />
    <input type="button" name="name" value="delete product" onclick="deleteProduct();" />*@


<br />
<input type="text" name="name" value="" id="Token" />
<br />

<script>
    window.Token = null;
    //  http://localhost:50619/api/Authentication/request  buradan token al
    //http://localhost:50619/api/values                  burada token ı kullan
    function getToken() {
        $.ajax({
            type: 'POST',
            url: 'http://localhost:50619/api/Authentication/request',
            data: '{username:"x", password:"y"}',
            contentType: 'application/json',
            success: function (resultData) {
                window.Token = resultData;
                $("#Token").val(resultData);
            },
            error: function (resultData) {
                console.log(resultData);
            }
        });
    }
    function getValues() {
        $.ajax({
            type: 'GET',
            //url: 'http://localhost:50619/api/values',
            url: 'http://localhost:50619/api/product',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            data: {},
            success: function (data) {
                //$.each(data, function (i) {
                //    console.log(data[i].name);
                //})
                alert("başarılı getvalues");
                for (var i = 0; i < data.length; i++) {
                    postValues(data[i]);
                }
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function getProduct() {
        $.ajax({
            type: 'GET',
            url: 'http://localhost:50619/api/product/3',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            data: {},
            success: function (data) {
                console.log(data);
                postValues(data);
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function postValues(data) {
        $.ajax({
            type: 'POST',
            //url: 'http://localhost:50619/api/values',
            //url: 'http://localhost:50619/api/product/1',
            //url: 'http://localhost:50619/api/product',
            url:'http://localhost:57374/api/products',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            contentType: 'application/json',
            dataType: 'json',
            //data: JSON.stringify({ Price: 67, Name: "aaaaaaa", Category: "ff" }),
            data: JSON.stringify(data),
            success: function (data) {
                console.log(data);
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function deleteProduct() {
        $.ajax({
            type: 'DELETE',
            //url: 'http://localhost:50619/api/values',
            //url: 'http://localhost:50619/api/product/1',
            url: 'http://localhost:50619/api/product/2',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            contentType: 'application/json',
            //data: JSON.stringify({ Price: 23, Name: "fdf", Category: "ff" }),
            data: {},
            success: function (data) {
                console.log(data);
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function putProduct() {
        $.ajax({
            type: 'PUT',
            url: 'http://localhost:50619/api/product/2',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("Authorization", "Bearer " + window.Token);// values alanına ulaşırken token ı eklemiş oldukç.
            },
            contentType: 'application/json',
            data: JSON.stringify({Id:2, Price: 11, Name: "g", Category: "r" }),
            success: function (data) {
                console.log(data);
            },
            error: function (data) {
                console.log(data);
            }
        });
    }

</script>



kpsUowRmqTest.Web/Views/Shared/Components/Menu/Default.cshtml

<div id="menu">
    <ul>
        <li> <a href="@Url.Action("Details", "User")" class="list-group-item">Kullanıcı</a></li>
        <li> <a href="@Url.Action("Details", "Product")" class="list-group-item">Ürün</a></li>


    </ul>
</div>


kpsUowRmqTest.Web/Views/Shared/_Layout.cshtml

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        #header {
            width: 900px;
            height: 100px;
            border-radius: 20px;
            background: red;
            padding: 20px;
            margin-bottom: 10px;
        }

        #menu {
            width: 200px;
            height: 300px;
            border-radius: 20px;
            /*background: blue;*/
            padding: 20px;
            float: left;
        }

        ul {
            margin: 0;
            padding: 0;
        }

        #menu li {
            list-style: none;
            padding: 10px;
        }

        #menu a {
            color: red;
            text-decoration: none;
        }

        #content {
            float: left;
            width: 650px;
            height: 300px;
            border-radius: 20px;
            /*background: blue;*/
            padding: 20px;
            margin-left: 10px;
        }


        #footer {
            width: 900px;
            height: 100px;
            border-radius: 20px;
            background: blue;
            padding: 20px;
            margin-top: 10px;
        }
    </style>
</head>
<body>

    <div class="row">
        <div class="col-md-4">@await Component.InvokeAsync("Menu")</div>
        <div class="col-md-8">
            @RenderBody()
        </div>
    </div>

    <div style="clear:both;"></div>



</body>
</html>

kpsUowRmqTest.Web/Views/User/Details.cshtml

@{
    ViewData["Title"] = "Details";
}

<h1>User Details</h1>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>


<br />
<input type="text" name="name" value="" id="Name" placeholder="Ad" />
<br />
<input type="text" name="surname" value="" id="Surname" placeholder="Soyad" />
<br />
<input type="text" name="tckn" value="" id="TCKN" placeholder="TCKN" />
<br />
<input type="text" name="year" value="" id="Year" placeholder="Yıl" />
<br />
<input type="button" name="name" value="User gonder" onclick="postUser();" />


<script>
    function postUser() {

        var TCKN = $("#TCKN").val();
        var Surname = $("#Surname").val();
        var Name = $("#Name").val();
        var Year = $("#Year").val();

        var objMainModel = {};

        objMainModel.Year = Year;
        objMainModel.Surname = Surname;
        objMainModel.Name = Name;
        objMainModel.TCKN = TCKN;

        $.ajax({
            type: "POST",
            url: 'http://localhost:57374/api/users',
            data: JSON.stringify(objMainModel),
            contentType: 'application/json',
            success: function (response) {

                //    if (response.IsSuccess) {
                //        $("#txt-Name").val(response.Name);
                //        $("#txt-Surname").val(response.Surname);
                //        hideLoader();
                //}
            },
            failure: function (response) {
                alert(response.responseText);
            }
        });

    }
</script>